import { streamChat } from "./llm";
import { modelById } from "../data/models";
import { providerById } from "../data/providers";
import type { ProviderCfg, ProjectFile } from "./store";
import { pickTemplate, deriveName } from "./templates";

/* ================= Coder: project generation ================= */

export interface ScaffoldResult {
  templateId: string;
  name: string;
  files: ProjectFile[];
}

/** Built-in generator — the offline safety net, produces real working files. */
export function scaffoldProject(desc: string): ScaffoldResult {
  const tpl = pickTemplate(desc);
  const name = deriveName(desc, tpl.id);
  const rec = tpl.build(name, desc);
  return {
    templateId: tpl.id,
    name,
    files: Object.entries(rec).map(([n, content]) => ({ name: n, content })),
  };
}

const LLM_PROMPT = (desc: string) =>
  `You are a senior frontend engineer. Create ONE self-contained web app (a single HTML file with <style> and <script> inside) for the brief below. UI in English, modern minimal design, everything must work immediately. Return ONLY one \`\`\`html code block with no text before or after.\n\nBrief: ${desc}`;

/** Try to generate the project with a real (free) model. Returns null on failure. */
export async function generateProjectWithLLM(
  desc: string,
  providerId: string,
  cfg: ProviderCfg | undefined,
  modelId: string,
  onLine: (line: string) => void,
  signal: AbortSignal
): Promise<ProjectFile[] | null> {
  const provider = providerById.get(providerId);
  const model = modelById.get(modelId);
  if (!provider || !model) return null;
  if (!provider.keyless && !provider.local && !cfg?.key?.trim()) {
    onLine(`⚠ ${provider.name} needs a key — falling back to the built-in generator`);
    return null;
  }
  try {
    onLine(`[FS] connected: ${provider.name} · ${model.name} (free)`);
    onLine("[FS] sending generation request…");
    let full = "";
    for await (const delta of streamChat({
      model,
      provider,
      cfg: cfg ?? { key: "", baseUrl: provider.baseUrl },
      messages: [{ role: "user", content: LLM_PROMPT(desc) }],
      params: { temperature: 0.4, topP: 0.95, maxTokens: 12000, system: "" },
      signal,
    })) {
      full += delta;
    }
    const html = extractHtmlBlock(full);
    if (!html) throw new Error("the model did not return a ```html block");
    onLine(`[FS] ✓ received ${(html.length / 1024).toFixed(1)} KB of code from ${model.name}`);
    return [
      { name: "index.html", content: html },
      {
        name: "README.md",
        content: `# App generated by ${model.name}\n\nBrief: ${desc}\n\nRun: open index.html in a browser.`,
      },
    ];
  } catch (e) {
    if (signal.aborted) throw e;
    const msg = e instanceof Error ? e.message : String(e);
    onLine(`⚠ LLM generation failed (${msg.slice(0, 90)})`);
    onLine("[ARCH] switching to the built-in generator…");
    return null;
  }
}

export function extractHtmlBlock(text: string): string | null {
  const m = /```html\s*\n([\s\S]*?)```/i.exec(text) ?? /```\s*\n(<!doctype[\s\S]*?)```/i.exec(text);
  return m ? m[1].trim() : null;
}

/** Assembles index.html with inlined css/js for the preview iframe. */
export function buildPreviewDoc(files: ProjectFile[]): string {
  const get = (n: string) => files.find((f) => f.name === n)?.content ?? "";
  let html = get("index.html") || files[0]?.content || "";
  const css = get("styles.css");
  const js = get("app.js");
  if (css) html = html.replace(/<link[^>]*styles\.css[^>]*>/i, `<style>\n${css}\n</style>`);
  if (js) html = html.replace(/<script[^>]*app\.js[^>]*><\/script>/i, `<script>\n${js}\n</script>`);
  return html;
}

/* ================= prompts ================= */

export const CODER_SUGGESTIONS = [
  "To-Do app with localStorage persistence",
  'Landing page for a coffee shop "Grain"',
  "Analytics dashboard with a sales chart",
  "Snake game on canvas",
  "Pomodoro timer with a progress ring",
  "Markdown notepad with autosave",
];
