import { pickTemplate, deriveName } from "./templates";
import { streamChat } from "./llm";
import { DEFAULT_PARAMS, type ProjectFile, type ProviderCfg } from "./store";
import { syntheticModel } from "../data/models";
import { providerById } from "../data/providers";

/** Deterministic offline generator — used when no free API is reachable. */
export function scaffoldProject(prompt: string): { name: string; templateId: string; files: ProjectFile[] } {
  const tpl = pickTemplate(prompt);
  const name = deriveName(prompt, tpl.id);
  const record = tpl.build(name, prompt);
  const order = ["index.html", "styles.css", "app.js", "README.md"];
  const files: ProjectFile[] = [];
  for (const k of order) {
    if (record[k]) files.push({ name: k, content: record[k] });
  }
  for (const [k, v] of Object.entries(record)) {
    if (!order.includes(k)) files.push({ name: k, content: v });
  }
  return { name, templateId: tpl.id, files };
}

/** Asks a live free model to generate the whole project as JSON. Returns null on failure. */
export async function generateProjectWithLLM(
  prompt: string,
  providerId: string,
  cfg: ProviderCfg | undefined,
  modelApiId: string,
  log: (line: string) => void,
  signal?: AbortSignal
): Promise<ProjectFile[] | null> {
  const provider = providerById.get(providerId);
  if (!provider || !cfg) return null;
  const keyOk = provider.keyless || provider.local || !!cfg.key?.trim();
  if (!keyOk) return null;

  const model = syntheticModel(providerId, modelApiId || "default");
  log(`[FE] generating with ${provider.name} · ${model.apiId}…`);

  const sys =
    "You are a senior web engineer. Create a small, complete, dependency-free web project (plain HTML/CSS/JS only, no frameworks, no CDN links) for the user's brief. " +
    'Reply ONLY with valid JSON in exactly this shape: {"files":[{"name":"index.html","content":"..."},{"name":"styles.css","content":"..."},{"name":"app.js","content":"..."},{"name":"README.md","content":"..."}]}. ' +
    "Files must be self-contained and work when opened in a browser. Keep each file under 250 lines.";

  let raw = "";
  try {
    for await (const d of streamChat({
      model,
      provider,
      cfg,
      messages: [
        { role: "system", content: sys },
        { role: "user", content: "Brief: " + prompt },
      ],
      params: { ...DEFAULT_PARAMS, temperature: 0.4, maxTokens: 8192 },
      signal,
    })) {
      raw += d;
    }
  } catch (e) {
    log("[FE] ⚠ generation failed: " + (e instanceof Error ? e.message : String(e)).slice(0, 120));
    return null;
  }

  const clean = raw.replace(/```(?:json)?/gi, "").trim();
  const start = clean.indexOf("{");
  const end = clean.lastIndexOf("}");
  if (start < 0 || end <= start) return null;
  try {
    const j = JSON.parse(clean.slice(start, end + 1));
    const files: ProjectFile[] = (j.files ?? [])
      .filter((f: any) => typeof f?.name === "string" && typeof f?.content === "string")
      .slice(0, 8)
      .map((f: any) => ({ name: f.name.replace(/[^\w.\-/]/g, "").slice(0, 64) || "file.txt", content: f.content }));
    if (!files.some((f) => f.name.endsWith(".html"))) {
      // wrap the payload so the preview still works
      files.unshift({
        name: "index.html",
        content: `<!doctype html><html><head><meta charset="utf-8"><title>Generated app</title><link rel="stylesheet" href="styles.css"></head><body><pre>${(files[0]?.content ?? "")
          .replace(/</g, "&lt;")
          .slice(0, 4000)}</pre></body></html>`,
      });
    }
    if (!files.some((f) => f.name === "README.md")) {
      files.push({ name: "README.md", content: `# Generated project\n\nBrief: ${prompt}\n\nGenerated by a live free model via ${provider.name}.` });
    }
    return files;
  } catch {
    return null;
  }
}

/** Inlines css/js into a single HTML document for the sandboxed preview iframe. */
export function buildPreviewDoc(files: ProjectFile[]): string {
  const html = files.find((f) => f.name.endsWith(".html"));
  if (!html) {
    const body = files.map((f) => `--- ${f.name} ---\n${f.content}`).join("\n\n");
    return `<!doctype html><html><head><meta charset="utf-8"></head><body><pre>${body.replace(/</g, "&lt;")}</pre></body></html>`;
  }
  const css = files.filter((f) => f.name.endsWith(".css")).map((f) => f.content).join("\n");
  const js = files.filter((f) => f.name.endsWith(".js")).map((f) => f.content).join("\n;\n");
  let doc = html.content;
  doc = doc.replace(/<link[^>]*rel=["']stylesheet["'][^>]*>/gi, "");
  doc = doc.replace(/<script[^>]*src=["'][^"']*["'][^>]*>\s*<\/script>/gi, "");
  const headIn = `<style>\n${css}\n</style>`;
  const bodyIn = `\n<script>\ntry {\n${js}\n} catch (e) { console.error(e); }\n</script>`;
  if (/<\/head>/i.test(doc)) doc = doc.replace(/<\/head>/i, headIn + "\n</head>");
  else doc = headIn + doc;
  if (/<\/body>/i.test(doc)) doc = doc.replace(/<\/body>/i, bodyIn + "\n</body>");
  else doc += bodyIn;
  return doc;
}
