import { useEffect, useMemo, useRef, useState } from "react";
import { modelById, MODELS, isAutoModel, resolveAutoModel } from "../data/models";
import { providerById, PROVIDERS } from "../data/providers";
import {
  scaffoldProject, generateProjectWithLLM, buildPreviewDoc, CODER_SUGGESTIONS,
} from "../lib/engine";
import { pickTemplate } from "../lib/templates";
import type { Project, ProjectFile, ProviderCfg } from "../lib/store";
import {
  BrandMark, Wordmark, SendIcon, CodeIcon, EyeIcon, TerminalIcon, RefreshIcon, PlayIcon,
  CheckIcon, FileIcon, OpenIcon,
} from "./Icons";

type Tab = "code" | "preview" | "term";

interface Props {
  project: Project | null;
  patchProject: (id: string, fn: (p: Project) => Project) => void;
  createProject: (prompt: string) => string;
  cfgs: Record<string, ProviderCfg>;
  modelId: string;
}

const COLOR_WORDS: Record<string, string> = {
  green: "#3ecf8e", teal: "#0f9d8f", aqua: "#35e0c2",
  violet: "#8b7cff", purple: "#8b7cff",
  blue: "#5b8cff", cyan: "#58c4dd",
  red: "#ff6b6b", pink: "#ff8ac2",
  yellow: "#ffc24b", orange: "#ff9950",
};

interface Step {
  label: string;
  state: "wait" | "run" | "done";
}

export default function CoderMode({ project, patchProject, createProject, cfgs, modelId }: Props) {
  const [prompt, setPrompt] = useState("");
  const [follow, setFollow] = useState("");
  const [tab, setTab] = useState<Tab>("code");
  const [fileIdx, setFileIdx] = useState(0);
  const [steps, setSteps] = useState<Step[]>([]);
  const [term, setTerm] = useState<string[]>([]);
  const [previewKey, setPreviewKey] = useState(0);
  const timers = useRef<number[]>([]);
  const termRef = useRef<HTMLDivElement>(null);
  const feedRef = useRef<HTMLDivElement>(null);

  const model = isAutoModel(modelId) ? resolveAutoModel(modelId, cfgs) : modelById.get(modelId) ?? MODELS[0];
  const provider = providerById.get(model.providerId) ?? PROVIDERS[0];
  const live = !!cfgs[model.providerId]?.key?.trim();
  const tplLabel = project ? pickTemplate(project.prompt).label : "";

  const later = (fn: () => void, ms: number) => {
    timers.current.push(window.setTimeout(fn, ms));
  };

  const log = (line: string) => setTerm((t) => [...t, line]);

  useEffect(() => {
    const el = termRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [term]);

  useEffect(() => {
    const el = feedRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [steps, term]);

  /* run the pipeline when the project enters the building state */
  useEffect(() => {
    if (!project || project.status !== "building") return;
    const pid = project.id;
    setSteps([]);
    setTerm([]);
    setTab("code");
    setFileIdx(0);

    const setStep = (i: number, state: Step["state"], label?: string) =>
      setSteps((s) => {
        const next = [...s];
        while (next.length <= i) next.push({ label: "", state: "wait" });
        next[i] = { label: label ?? next[i].label, state };
        return next;
      });

    setStep(0, "run", "Analyzing request & planning structure");
    log(`⏺ AiDe Coder · model ${model.name} (${provider.name})`);
    log("⏺ Task: " + project.prompt);

    let cancelled = false;
    const ac = new AbortController();

    (async () => {
      let files: ProjectFile[] = [];
      let tplId = project.templateId;

      const llmFiles = await generateProjectWithLLM(
        project.prompt, model.providerId, cfgs[model.providerId], model.id,
        (l) => log(l), ac.signal
      ).catch(() => null);

      if (cancelled) return;
      if (llmFiles) {
        files = llmFiles;
        tplId = "llm";
        log("✓ Project generated by the real model");
      } else {
        const sc = scaffoldProject(project.prompt);
        files = sc.files;
        tplId = sc.templateId;
        log("⏺ Template: " + pickTemplate(project.prompt).label);
      }

      later(() => setStep(0, "done"), 0);
      later(() => {
        setStep(1, "run", "Creating project files");
        log(`⏺ Structure: ${files.length} files`);
      }, 500);

      files.forEach((f, i) => {
        later(() => {
          setSteps((s) => s.map((st, j) => (j === 1 ? { ...st, label: `Creating project files (${i + 1}/${files.length})` } : st)));
          log("  + " + f.name + "  (" + f.content.split("\n").length + " lines)");
          patchProject(pid, (p) => ({ ...p, files: [...p.files, f], templateId: tplId }));
          setFileIdx(i);
        }, 900 + i * 620);
      });

      const t1 = 900 + files.length * 620;
      later(() => {
        setStep(1, "done");
        setStep(2, "run", "Building preview bundle");
        log("⏺ bundling — inlining styles and scripts…");
      }, t1 + 300);
      later(() => {
        log("✓ dist/index.html built (" + (files.reduce((s, f) => s + f.content.length, 0) / 1024).toFixed(1) + " KB)");
        setStep(2, "done");
        setStep(3, "done", "Preview is live");
        patchProject(pid, (p) => ({ ...p, status: "ready" }));
        setTab("preview");
        setPreviewKey((k) => k + 1);
      }, t1 + 1400);
    })();

    return () => {
      cancelled = true;
      ac.abort();
      timers.current.forEach(clearTimeout);
      timers.current = [];
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [project?.id, project?.status === "building"]);

  if (!project) {
    return (
      <div className="h-full overflow-y-auto">
        <div className="mx-auto flex min-h-full w-full max-w-[700px] flex-col justify-center px-6 py-12">
          <p className="overline">coder · scaffolds working apps</p>
          <h1 className="mt-4 font-display text-[clamp(26px,3.4vw,42px)] font-bold leading-tight">
            <Wordmark className="text-inherit" /> <span className="text-gold">Coder</span>
          </h1>
          <p className="mt-4 max-w-[540px] text-[14.5px] leading-relaxed text-dim">
            Describe an app and I'll build it from scratch — files, styles, logic and a live preview
            you can click.
            {live
              ? ` Generation runs on ${model.name}.`
              : " Demo mode uses the built-in generator; add an API key for real model output."}
          </p>
          <p className="mt-4 flex flex-wrap items-center gap-2 font-mono text-[11px] text-faint">
            <span>describe</span>
            <span className="text-brand">→</span>
            <span>files generated</span>
            <span className="text-brand">→</span>
            <span>live preview</span>
            <span className="text-brand">→</span>
            <span>iterate</span>
          </p>

          {/* terminal-style composer */}
          <div className="composer-glow mt-7 overflow-hidden rounded-2xl border border-line2 bg-panel2">
            <div className="flex items-center gap-1.5 border-b border-line px-4 py-2">
              {["#ff6b6b", "#ffc24b", "#31e5ae"].map((c) => (
                <span key={c} className="h-2.5 w-2.5 rounded-full opacity-70" style={{ background: c }} />
              ))}
              <span className="ml-2 font-mono text-[10.5px] text-faint">~/projects — aide new</span>
              <span className="ml-auto hidden font-mono text-[9.5px] uppercase tracking-[0.18em] text-faint sm:block">
                {live ? `model · ${model.name}` : "built-in generator"}
              </span>
            </div>
            <div className="flex items-start gap-2.5 p-3.5">
              <span className="mt-2 font-mono text-[13px] font-bold text-brand">$</span>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    if (prompt.trim()) createProject(prompt.trim());
                  }
                }}
                rows={2}
                placeholder={'a landing page for a coffee shop "Grain"'}
                className="flex-1 resize-none bg-transparent py-1.5 font-mono text-[13.5px] leading-relaxed outline-none placeholder:text-faint"
              />
              <button
                onClick={() => prompt.trim() && createProject(prompt.trim())}
                disabled={!prompt.trim()}
                className="btn-brand flex h-10 w-10 shrink-0 items-center justify-center rounded-xl disabled:opacity-35 disabled:saturate-50"
                title="Create project (Enter)"
              >
                <PlayIcon className="h-4 w-4" />
              </button>
            </div>
          </div>

          <p className="overline mb-3 mt-8">or start from</p>
          <div className="flex flex-wrap gap-2">
            {CODER_SUGGESTIONS.map((s, i) => (
              <button
                key={s}
                style={{ animationDelay: `${i * 60}ms` }}
                onClick={() => createProject(s)}
                className="anim-rise group flex items-center gap-2 rounded-full border border-line bg-panel/70 py-1.5 pl-2.5 pr-3.5 text-[12.5px] text-dim transition-all hover:-translate-y-0.5 hover:border-brand/45 hover:text-text"
              >
                <span className="font-mono text-[11px] text-brand">+</span>
                {s}
              </button>
            ))}
          </div>
        </div>
      </div>
    );
  }

  const previewDoc = useMemo(() => buildPreviewDoc(project.files), [project.files, previewKey]);
  const current = project.files[Math.min(fileIdx, Math.max(0, project.files.length - 1))];

  function applyFollowUp() {
    const text = follow.trim();
    if (!text || !project || project.status !== "ready") return;
    setFollow("");
    const low = text.toLowerCase();
    const logs: string[] = [];
    let files = project.files.map((f) => ({ ...f }));

    const colorKey = Object.keys(COLOR_WORDS).find((k) => low.includes(k));
    if (colorKey) {
      const hex = COLOR_WORDS[colorKey];
      files = files.map((f) =>
        f.name.endsWith(".css")
          ? {
              ...f,
              content: f.content
                .replace(/(--accent:\s*)#[0-9a-fA-F]{3,8}/, "$1" + hex)
                .replace(/#0f9d8f/gi, hex)
                .replace(/#0c8377/gi, hex),
            }
          : f
      );
      logs.push("⏺ Accent color updated → " + hex);
    }
    const quoted = text.match(/["«”]([^"»”]{2,40})["»”]/);
    if (quoted) {
      files = files.map((f) =>
        f.name === "index.html"
          ? { ...f, content: f.content.replace(/<title>[^<]*<\/title>/, "<title>" + quoted[1] + "</title>") }
          : f
      );
      logs.push('⏺ Title → "' + quoted[1] + '"');
    }
    if (!logs.length) logs.push("⏺ Request analyzed — no major changes needed");

    log("— change request: " + text);
    logs.forEach(log);
    log("✓ rebuilt dist/index.html");
    patchProject(project.id, (p) => ({ ...p, files, name: quoted ? quoted[1] : p.name }));
    setPreviewKey((k) => k + 1);
  }

  function openPreview() {
    const blob = new Blob([previewDoc], { type: "text/html;charset=utf-8" });
    window.open(URL.createObjectURL(blob), "_blank");
  }

  return (
    <div className="flex h-full">
      {/* ------- agent feed ------- */}
      <div className="flex w-[340px] shrink-0 flex-col border-r border-line bg-panel/40 max-lg:w-[280px] max-md:hidden">
        <div className="border-b border-line px-4 py-3">
          <div className="flex items-center gap-2.5">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg border border-gold/30 bg-gold/8">
              <CodeIcon className="h-4 w-4 text-gold" />
            </span>
            <div className="min-w-0">
              <p className="truncate text-[13.5px] font-bold">{project.name}</p>
              <p className="truncate font-mono text-[10.5px] text-faint">
                {tplLabel} · {project.files.length} files ·{" "}
                {project.status === "ready" ? <span className="text-mint">ready</span> : <span className="text-gold">building…</span>}
              </p>
            </div>
          </div>
          <p className="mt-2 rounded-lg bg-panel2 px-3 py-2 text-[12px] italic leading-snug text-dim">“{project.prompt}”</p>
        </div>

        <div ref={feedRef} className="flex-1 space-y-1.5 overflow-y-auto px-4 py-4">
          {steps.map((s, i) => (
            <div key={i} className="step-in flex items-center gap-2.5 text-[12.5px]">
              {s.state === "done" ? (
                <span className="flex h-4.5 w-4.5 shrink-0 items-center justify-center rounded-full bg-mint/15 text-mint"><CheckIcon className="h-3 w-3" /></span>
              ) : s.state === "run" ? (
                <span className="h-4.5 w-4.5 shrink-0 animate-spin rounded-full border-[2px] border-brand/25 border-t-brand" />
              ) : (
                <span className="h-4.5 w-4.5 shrink-0 rounded-full border border-line2" />
              )}
              <span className={s.state === "wait" ? "text-faint" : "text-text"}>{s.label}</span>
            </div>
          ))}
          {project.status === "ready" && (
            <div className="step-in mt-3 rounded-xl border border-line bg-panel px-3 py-2.5 text-[12px] leading-relaxed text-dim">
              The project is ready — try it in <b className="text-brand">Preview</b>. Ask for changes like{" "}
              <i>“make the accent green”</i> or <i>“rename it to "My App"”</i>.
            </div>
          )}
        </div>

        <div className="border-t border-line p-3">
          <div className="flex items-end gap-2 rounded-xl border border-line bg-panel2 p-2 transition-all focus-within:border-brand/50">
            <textarea
              value={follow}
              onChange={(e) => setFollow(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  applyFollowUp();
                }
              }}
              rows={1}
              placeholder={project.status === "ready" ? "Ask for a change…" : "Agent is working…"}
              disabled={project.status !== "ready"}
              className="flex-1 resize-none bg-transparent px-1.5 py-1 text-[13px] outline-none placeholder:text-faint disabled:opacity-50"
            />
            <button
              onClick={applyFollowUp}
              disabled={!follow.trim() || project.status !== "ready"}
              className="btn-brand flex h-8 w-8 shrink-0 items-center justify-center rounded-lg disabled:opacity-30"
            >
              <SendIcon className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>
      </div>

      {/* ------- workspace ------- */}
      <div className="flex min-w-0 flex-1 flex-col">
        <div className="flex items-center gap-1 border-b border-line px-3 py-2">
          {(
            [
              { id: "code", label: "Code", icon: CodeIcon },
              { id: "preview", label: "Preview", icon: EyeIcon },
              { id: "term", label: "Terminal", icon: TerminalIcon },
            ] as const
          ).map((t) => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[12.5px] font-semibold transition-all ${
                tab === t.id ? "bg-brand/12 text-brand" : "text-dim hover:bg-panel2 hover:text-text"
              }`}
            >
              <t.icon className="h-3.5 w-3.5" />
              {t.label}
            </button>
          ))}
          <div className="ml-auto flex items-center gap-1.5">
            {tab === "preview" && (
              <>
                <button className="icon-btn" onClick={() => setPreviewKey((k) => k + 1)} title="Reload preview">
                  <RefreshIcon className="h-3.5 w-3.5" />
                </button>
                <button className="icon-btn" onClick={openPreview} title="Open in a new tab">
                  <OpenIcon className="h-3.5 w-3.5" />
                </button>
              </>
            )}
            {project.status === "ready" && (
              <button
                onClick={() => {
                  patchProject(project.id, (p) => ({ ...p, status: "building", files: [] }));
                }}
                className="flex items-center gap-1.5 rounded-lg border border-line px-2.5 py-1.5 text-[11.5px] font-semibold text-dim transition-all hover:border-brand/45 hover:text-brand"
                title="Rebuild the project from scratch"
              >
                <RefreshIcon className="h-3.5 w-3.5" /> Rebuild
              </button>
            )}
          </div>
        </div>

        {tab === "code" && (
          <div className="flex min-h-0 flex-1">
            <div className="w-[190px] shrink-0 overflow-y-auto border-r border-line bg-panel/50 p-2">
              <p className="overline px-2 pb-1.5 pt-1">files</p>
              {project.files.length === 0 && (
                <p className="px-2 py-3 text-[11.5px] text-faint">The agent is creating files…</p>
              )}
              {project.files.map((f, i) => (
                <button
                  key={f.name}
                  onClick={() => setFileIdx(i)}
                  className={`step-in flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-left font-mono text-[11.5px] transition-colors ${
                    i === Math.min(fileIdx, project.files.length - 1) ? "bg-brand/12 text-brand" : "text-dim hover:bg-panel2"
                  }`}
                >
                  <FileIcon className="h-3.5 w-3.5 shrink-0" />
                  <span className="truncate">{f.name}</span>
                </button>
              ))}
            </div>
            <div className="min-w-0 flex-1 overflow-auto bg-ink/60">
              {current ? (
                <div>
                  <div className="sticky top-0 z-10 flex items-center gap-2 border-b border-line bg-panel/90 px-4 py-2 backdrop-blur">
                    <span className="font-mono text-[11.5px] text-brand">{current.name}</span>
                    <span className="font-mono text-[10px] text-faint">
                      {current.content.split("\n").length} lines · {(current.content.length / 1024).toFixed(1)} KB
                    </span>
                  </div>
                  <pre className="px-4 py-3 font-mono text-[12px] leading-[1.65]">
                    {current.content.split("\n").map((line, i) => (
                      <div key={i} className="flex">
                        <span className="mr-4 w-7 shrink-0 select-none text-right text-faint/60">{i + 1}</span>
                        <span className="whitespace-pre-wrap break-all text-[#c9d6de]">{line || " "}</span>
                      </div>
                    ))}
                  </pre>
                </div>
              ) : (
                <div className="flex h-full items-center justify-center">
                  <span className="flex items-center gap-2 font-mono text-[12px] text-faint">
                    <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-brand/25 border-t-brand" />
                    generating files…
                  </span>
                </div>
              )}
            </div>
          </div>
        )}

        {tab === "preview" && (
          <div className="min-h-0 flex-1 bg-[#0c0e12] p-0">
            {project.files.length ? (
              <iframe
                key={previewKey}
                title="Project preview"
                sandbox="allow-scripts allow-modals"
                srcDoc={previewDoc}
                className="h-full w-full border-0 bg-white"
              />
            ) : (
              <div className="flex h-full items-center justify-center font-mono text-[12px] text-faint">
                the preview appears after the build…
              </div>
            )}
          </div>
        )}

        {tab === "term" && (
          <div className="term-scan relative min-h-0 flex-1 overflow-hidden bg-[#07090c]">
            <div ref={termRef} className="h-full overflow-y-auto px-4 py-3 font-mono text-[12px] leading-relaxed">
              {term.map((l, i) => (
                <p
                  key={i}
                  className={`term-line whitespace-pre-wrap ${
                    l.startsWith("✓") ? "text-mint" : l.startsWith("⚠") ? "text-gold" : l.startsWith("—") ? "text-brand" : l.startsWith("  +") ? "text-cyanic" : "text-dim"
                  }`}
                >
                  {l}
                </p>
              ))}
              {project.status === "building" && <span className="caret" />}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
